# Site settings
title: algenonQ - the Blog
#email: xxyour-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog describing the progress and plans for all my github projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://algenonq.github.io" # the base hostname & protocol for your site
github_username:  algenonq

# Build settings
markdown: kramdown
